#!/usr/bin/env bash
# Static contract checks are intentionally runnable without an OpenHarmony NDK.
set -euo pipefail
root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
build="$root/build.sh"; smb="$root/build-libsmbclient.sh"; deps="$root/build-libdeps.sh"; verify="$root/verify.sh"
grep -Fq -- '--disable-static' "$build"
grep -Fq -- '--enable-shared' "$build"
grep -Fq -- '--enable-pic' "$build"
grep -Fq -- '--enable-cross-compile' "$build"
grep -Fq -- '--enable-mbedtls' "$build"
! grep -Fq -- '--enable-gnutls' "$build"
grep -Fq -- '--enable-zlib' "$build"
grep -Fq -- '--enable-libdav1d' "$build"
grep -Fq -- '--enable-libxml2' "$build"
grep -Fq -- '--enable-demuxer=dash' "$build"
grep -Fq -- '--enable-ohcodec' "$build"
grep -Fq -- '--enable-encoder=png,mjpeg' "$build"
grep -Fq -- '--enable-protocol=file,http,https,tls,tcp,httpproxy,rtmp,rtp,udp,crypto,data,pipe,concat,subfile,cache,async,smb' "$build"
grep -Fq 'CONFIG_HTTPS_PROTOCOL' "$build"
grep -Fq 'CONFIG_TLS_PROTOCOL' "$build"
grep -Fq 'CONFIG_MBEDTLS' "$build"
grep -Fq 'CONFIG_LIBDAV1D_DECODER' "$build"
grep -Fq 'CONFIG_LIBXML2' "$build"
grep -Fq 'CONFIG_DASH_DEMUXER' "$build"
grep -Fq 'CONFIG_OHCODEC' "$build"
grep -Fq 'CONFIG_PNG_ENCODER' "$build"
grep -Fq 'CONFIG_MJPEG_ENCODER' "$build"
grep -Fq 'protocols.txt' "$build"
grep -Fq 'mbedtls_ssl_handshake' "$verify"
grep -Fq 'xmlParseStartTag' "$verify"
grep -Fq 'libdav1d' "$verify"
grep -Fq 'OH_VideoDecoder_CreateByName' "$verify"
grep -Fq -- '--enable-libsmbclient' "$build"
grep -Fq -- '--enable-gpl' "$build"
grep -Fq -- '--enable-version3' "$build"
grep -Fq -- '--pkg-config-flags=--static' "$build"
grep -Fq 'PKG_CONFIG_LIBDIR="$SMB_SYSROOT/lib/pkgconfig"' "$build"
grep -Fq 'MBEDTLS_SHA256' "$deps"
grep -Fq 'DAV1D_SHA256' "$deps"
grep -Fq 'LIBXML2_SHA256' "$deps"
grep -Fq 'V_MBEDTLS=3.6.4' "$deps"
grep -Fq 'V_DAV1D=1.5.1' "$deps"
grep -Fq 'V_LIBXML2=2.15.1' "$deps"
grep -Fq 'libmbedtls.a' "$deps"
grep -Fq 'libdav1d.a' "$deps"
grep -Fq 'libxml2.a' "$deps"
grep -Fq "'s|^prefix=.*$|prefix=\${pcfiledir}/../..|'" "$build"
grep -Fq "'s|^exec_prefix=.*$|exec_prefix=\${prefix}|'" "$build"
grep -Fq "'s|^libdir=.*$|libdir=\${exec_prefix}/lib|'" "$build"
grep -Fq "'s|^includedir=.*$|includedir=\${prefix}/include|'" "$build"
grep -Fq 'libsmbclient_linkage=static-closure' "$build"
grep -Fq 'libav*.a' "$verify"
grep -Fq 'libsmbclient\.so' "$verify"
grep -Fq 'lib(gnutls|tasn1|nettle|hogweed|gmp|popt|z|mbedtls|mbedcrypto|mbedx509|dav1d|xml2)\.so' "$verify"
grep -Fq 'ELF64' "$verify"
grep -Fq 'libsmbclient' "$verify"
grep -Fq 'SAMBA_ARCHIVE_SHA256' "$smb"
grep -Fq 'https://www.mirrorservice.org/sites/ftp.gnupg.org/gcrypt/gnutls/v3.8/gnutls-3.8.7.tar.xz' "$smb"
! grep -Fq 'https://www.gnupg.org/ftp/gcrypt/gnutls/v3.8/gnutls-3.8.7.tar.xz' "$smb"
grep -Fq 'Libs.private:' "$smb"
grep -Fq -- "--with-static-modules='ALL,!vfs_snapper'" "$smb"
grep -Fq -- "--with-shared-modules='!DEFAULT,!vfs_snapper'" "$smb"
grep -Fq 'Checking whether we can use Linux thread-specific credentials: NO' "$smb"
! grep -Fq 'git reset --hard' "$smb"
echo 'FFmpeg 8 SMB SDK contract test passed'
